name: Build APK
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'APK tag (version name)'
        required: true
        default: '3.8.2'
      type:
        description: 'Environment type'
        type: choice
        options:
          - 'production'
          - 'staging'
        required: true
        default: 'production'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Delete 'signingConfig signingConfigs.release' line
        run: cd android && cd app && sed '/signingConfig signingConfigs.release/d' build.gradle > build.gradle.tmp && mv build.gradle.tmp build.gradle
      - name: Delete 'keystoreProperties['storeFile'])' line
        run: sed '/storeFile file(keystoreProperties/d' build.gradle > build.gradle.tmp && mv build.gradle.tmp build.gradle && cd .. && cd ..

      - name: Build APK
        run: flutter build apk --flavor ${{ github.event.inputs.type }}

      - name: Push to Release
        id: push_to_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-${{ github.event.inputs.type }}-release.apk
          tag: v${{ github.event.inputs.tag }}-${{ github.event.inputs.type }}
          token: ${{ secrets.TOKEN }}
      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "New build available | ${{ github.event.inputs.type }} | v${{ github.event.inputs.tag }}",
              "blocks": [
                {
                  "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Download",
                        "emoji": true
                    },
                    "url": "${{ steps.push_to_release.outputs.artifact_url }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
