name: Build and Release APK
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'APK tag (version name)'
        required: true
        default: '3.8.2'
      type:
        description: 'Environment type'
        type: choice
        options:
          - 'production'
          - 'staging'
        required: true
        default: 'production'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --flavor ${{ github.event.inputs.type }}

      - name: Push to Release
        id: push_to_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-${{ github.event.inputs.type }}-release.apk
          tag: v${{ github.event.tag }}
          token: ${{ secrets.TOKEN }}
