name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'APK type'
        options:
          - 'release'
          - 'debug'
        required: true
        default: 'release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --${{ github.event.inputs.type }}
        
      - name: Get version from pubspec
        id: get_version
        run: echo ::set-output name=version::$(awk '/version/{gsub(/"/,""); print $NF}' pubspec.yaml)

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-${{ github.event.inputs.type }}.apk
          asset_name: MyApp-${{ github.event.inputs.type }}.apk
          asset_content_type: application/vnd.android.package-archive
