name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'APK tag (version name)'
        required: true
        default: '0.0'
      type:
        description: 'APK type'
        type: choice
        options:
          - 'release'
          - 'debug'
        required: true
        default: 'release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --${{ github.event.inputs.type }}
        
      - name: Get version from pubspec
        id: get_version
        run: echo ::set-output name=version::$(awk '/version/{gsub(/"/,""); print $NF}' pubspec.yaml)

      - name: Push to Release
        id: push_to_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-${{ github.event.inputs.type }}.apk
          tag: v${{ github.event.inputs.tag }}-${{ github.event.inputs.type }}
          token: ${{ secrets.TOKEN }}
          
      - name: Send email with release link
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          encryption: tls
          subject: Release APK v${{ github.event.inputs.tag }}-${{ github.event.inputs.type }}
          body: |
            Hello team,
            
            We have released a new APK version: v${{ github.event.inputs.tag }}-${{ github.event.inputs.type }}.
            You can download it from the following link:
            
            Download link: [Download APK](https://example.com/path/to/release)

          from: vivek.kumar@askfilo.com
          to: ujjawal.tiwari@askfilo.com
