name: Build APK
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'APK tag (version name)'
        required: true
        default: '3.8.2'
      type:
        description: 'Environment type'
        type: choice
        options:
          - 'production'
          - 'staging'
        required: true
        default: 'production'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Delete 'signingConfig signingConfigs.release' and 'keystoreProperties['storeFile'])' lines
        run: cd android && cd app && ls && sed -i.bak -e '/signingConfig signingConfigs.release/d' -e '/storeFile file(keystoreProperties/d' ./build.gradle && ls && cd .. && cd ..

      - name: Build APK
        run: flutter build apk --flavor ${{ github.event.inputs.type }}

      - name: Extract version
        id: extract_version
        run: |
          version=$(sed -n 's/version: \(.*\)+.*/\1/p' pubspec.yaml)
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Push to Release
        id: push_to_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-${{ github.event.inputs.type }}-release.apk
          tag: v${{ env.VERSION }}-${{ github.event.inputs.type }}
          token: ${{ secrets.TOKEN }}
